name: Avenue CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  mac:
    name: Build
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build Avenue GPX Viewer
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Avenue.xcodeproj" -scheme "Avenue" -destination "platform=macOS" clean build | xcpretty
